name: smartagro
region: sgp  # Singapore (closest to Ghana)

# Environment variables (these will be set in DO dashboard)
envs:
  - key: ENVIRONMENT
    value: production
  - key: DEBUG
    value: "False"

services:
  # Backend API Service
  - name: backend
    github:
      repo: Ashesi-Org/Team-SoftTouch
        # UPDATE THIS with your actual GitHub username/repo
      branch: main
      deploy_on_push: true
    
    source_dir: /backend
    
    # Build configuration
    build_command: pip install -r requirements.txt && alembic upgrade head
    
    # Run configuration
    run_command: uvicorn main:app --host 0.0.0.0 --port $PORT
    
    # Environment
    environment_slug: python
    
    # Instance size
    instance_size_slug: basic-xs  # 512MB RAM, $5/month
    instance_count: 1
    
    # Health check
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    # HTTP configuration
    http_port: 8000
    
    # Routes
    routes:
      - path: /api
    
    # Environment variables (injected by DO)
    envs:
      # Auto-injected by DO
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: REDIS_URL
        scope: RUN_TIME
        type: SECRET
      
      # You must set these manually in DO dashboard:
      # - MONGODB_URI
      # - PAYSTACK_SECRET_KEY
      # - PAYSTACK_PUBLIC_KEY
      # - MNOTIFY_API_KEY
      # - OPENROUTER_API_KEY
      # - OPENWEATHER_API_KEY
      # - OPENAI_API_KEY
      # - SPACES_ACCESS_KEY
      # - SPACES_SECRET_KEY
      # - JWT_SECRET_KEY
      # - SECRET_KEY
      # - FRONTEND_URL

# Databases
databases:
  # PostgreSQL
  - name: smartagro-postgres
    engine: PG
    version: "15"
    production: false  # Set to true for production
    cluster_name: smartagro-db-cluster
    db_name: smartagro
    db_user: smartagro_user
    size: db-s-1vcpu-1gb  # 1GB RAM, 10GB storage, $15/month
  
  # Valkey (Redis-compatible)
  - name: smartagro-valkey
    engine: REDIS  # Valkey uses REDIS engine type in DO
    version: "7"
    production: false  # Set to true for production
    size: db-s-1vcpu-1gb  # 1GB RAM, $15/month

static_sites:
  - name: frontend
    github:
      repo: Ashesi-Org/Team-SoftTouch

      branch: main
      deploy_on_push: true
    source_dir: /frontend
    build_command: npm run build
    output_dir: dist
    environment_slug: node-js
    envs:
      - key: VITE_API_URL
        value: ${backend.PUBLIC_URL}

# Jobs (optional - for background tasks)
# jobs:
#   - name: cleanup-job
#     github:
#       repo: your-username/smartagro
#       branch: main
#     source_dir: /backend
#     run_command: python -m utils.cleanup_jobs
#     environment_slug: python
#     kind: CRON
#     schedule: "0 3 * * *"  # Daily at 3 AM