"""Initial migration

Revision ID: 8f0d890501b0
Revises: 
Create Date: 2025-12-06 21:28:52.303802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = '8f0d890501b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Check if tables already exist to avoid DuplicateTable error
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()
    
    if 'crop_knowledge' in tables and 'users' in tables:
        print("Skipping initial migration as tables already exist")
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_knowledge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('crop_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('local_name_twi', sa.String(length=100), nullable=True),
    sa.Column('local_name_ga', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('reliability_score', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('applicable_regions', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('planting_season', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crop_category', 'crop_knowledge', ['category'], unique=False)
    op.create_index('idx_crop_name', 'crop_knowledge', ['crop_name'], unique=False)
    op.create_index(op.f('ix_crop_knowledge_crop_name'), 'crop_knowledge', ['crop_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('user_type', sa.Enum('FARMER', 'BUYER', 'ADMIN', name='usertype'), nullable=False),
    sa.Column('profile_image_url', sa.Text(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_method', sa.String(length=20), nullable=True),
    sa.Column('verification_document_url', sa.Text(), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('town_city', sa.String(length=100), nullable=True),
    sa.Column('gps_address', sa.String(length=50), nullable=True),
    sa.Column('detailed_address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=11, scale=8), nullable=True),
    sa.Column('wallet_balance', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('bank_code', sa.String(length=10), nullable=True),
    sa.Column('account_number', sa.String(length=20), nullable=True),
    sa.Column('account_name', sa.String(length=255), nullable=True),
    sa.Column('paystack_recipient_code', sa.String(length=255), nullable=True),
    sa.Column('paystack_subaccount_code', sa.String(length=255), nullable=True),
    sa.Column('account_status', sa.Enum('ACTIVE', 'SUSPENDED', 'PENDING_VERIFICATION', 'DELETED', name='accountstatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('language_preference', sa.String(length=10), nullable=False),
    sa.Column('notification_enabled', sa.Boolean(), nullable=False),
    sa.Column('sms_notification_enabled', sa.Boolean(), nullable=False),
    sa.Column('farm_name', sa.String(length=255), nullable=True),
    sa.Column('farm_size_acres', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('years_farming', sa.Integer(), nullable=True),
    sa.Column('average_rating', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('total_sales', sa.Integer(), nullable=False),
    sa.Column('total_purchases', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paystack_recipient_code'),
    sa.UniqueConstraint('paystack_subaccount_code')
    )
    op.create_index('idx_user_location', 'users', ['region', 'district'], unique=False)
    op.create_index('idx_user_type_status', 'users', ['user_type', 'account_status'], unique=False)
    op.create_index('idx_user_verified', 'users', ['is_verified', 'user_type'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_user_type'), 'users', ['user_type'], unique=False)
    op.create_table('admin_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('RESOLVE_DISPUTE', 'SUSPEND_USER', 'ACTIVATE_USER', 'DELETE_PRODUCT', 'VERIFY_USER', 'REFUND_PAYMENT', 'RELEASE_PAYMENT', 'UPDATE_USER', name='adminactiontype'), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_admin_action_target', 'admin_actions', ['target_type', 'target_id'], unique=False)
    op.create_index('idx_admin_action_type_time', 'admin_actions', ['action_type', 'timestamp'], unique=False)
    op.create_index(op.f('ix_admin_actions_action_type'), 'admin_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_admin_actions_admin_id'), 'admin_actions', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_actions_timestamp'), 'admin_actions', ['timestamp'], unique=False)
    op.create_table('otp_verifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('otp_code', sa.String(length=6), nullable=False),
    sa.Column('otp_type', sa.Enum('EMAIL_VERIFICATION', 'PHONE_VERIFICATION', 'PASSWORD_RESET', 'TRANSACTION_CONFIRM', name='otptype'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('is_expired', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_otp_expiry', 'otp_verifications', ['expires_at', 'is_used'], unique=False)
    op.create_index('idx_otp_user_type', 'otp_verifications', ['user_id', 'otp_type', 'is_used'], unique=False)
    op.create_index(op.f('ix_otp_verifications_user_id'), 'otp_verifications', ['user_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('VEGETABLES', 'FRUITS', 'TUBERS', 'GRAINS', 'CEREALS', 'LEGUMES', 'LIVESTOCK', 'DAIRY', 'OTHER', name='productcategory'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity_available', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('unit_of_measure', sa.Enum('KG', 'GRAMS', 'BAGS', 'CRATES', 'PIECES', 'BUNCHES', 'LITERS', name='unitofmeasure'), nullable=False),
    sa.Column('price_per_unit', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('minimum_order_quantity', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('harvest_date', sa.Date(), nullable=True),
    sa.Column('expected_shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('expiry_alert_days', sa.Integer(), nullable=False),
    sa.Column('farm_location', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('gps_coordinates', sa.String(length=100), nullable=True),
    sa.Column('primary_image_url', sa.Text(), nullable=True),
    sa.Column('additional_images', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('is_organic', sa.Boolean(), nullable=False),
    sa.Column('certification_details', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'SOLD', 'RESERVED', 'EXPIRED', 'DELETED', name='productstatus'), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_negotiable', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('order_count', sa.Integer(), nullable=False),
    sa.Column('total_sold', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_category_status', 'products', ['category', 'status'], unique=False)
    op.create_index('idx_product_created', 'products', ['created_at'], unique=False)
    op.create_index('idx_product_seller_status', 'products', ['seller_id', 'status'], unique=False)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_created_at'), 'products', ['created_at'], unique=False)
    op.create_index(op.f('ix_products_seller_id'), 'products', ['seller_id'], unique=False)
    op.create_index(op.f('ix_products_status'), 'products', ['status'], unique=False)
    op.create_table('system_configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity_ordered', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('platform_fee', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('delivery_fee', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('delivery_address', sa.Text(), nullable=False),
    sa.Column('delivery_region', sa.String(length=50), nullable=True),
    sa.Column('delivery_district', sa.String(length=100), nullable=True),
    sa.Column('delivery_gps', sa.String(length=50), nullable=True),
    sa.Column('delivery_phone', sa.String(length=20), nullable=True),
    sa.Column('delivery_notes', sa.Text(), nullable=True),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('actual_delivery_date', sa.Date(), nullable=True),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('tracking_notes', sa.Text(), nullable=True),
    sa.Column('buyer_notes', sa.Text(), nullable=True),
    sa.Column('seller_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PAYMENT_INITIATED', 'PAID', 'CONFIRMED', 'SHIPPED', 'IN_TRANSIT', 'DELIVERED', 'COMPLETED', 'CANCELLED', 'DISPUTED', 'REFUNDED', name='orderstatus'), nullable=False),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('cancelled_reason', sa.Text(), nullable=True),
    sa.Column('cancelled_by_user_id', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cancelled_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_reference')
    )
    op.create_index('idx_order_buyer_status', 'orders', ['buyer_id', 'status'], unique=False)
    op.create_index('idx_order_seller_status', 'orders', ['seller_id', 'status'], unique=False)
    op.create_index('idx_order_status_created', 'orders', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_orders_buyer_id'), 'orders', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_product_id'), 'orders', ['product_id'], unique=False)
    op.create_index(op.f('ix_orders_seller_id'), 'orders', ['seller_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('escrow_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('platform_fee', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('seller_payout', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('paystack_reference', sa.String(length=255), nullable=True),
    sa.Column('paystack_status', sa.String(length=50), nullable=True),
    sa.Column('paystack_transfer_code', sa.String(length=255), nullable=True),
    sa.Column('paystack_paid_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PAYMENT_INITIATED', 'HELD', 'RELEASED', 'REFUNDED', 'DISPUTED', 'PARTIALLY_REFUNDED', name='escrowstatus'), nullable=False),
    sa.Column('auto_release_date', sa.DateTime(), nullable=True),
    sa.Column('dispute_deadline', sa.DateTime(), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('released_to_user_id', sa.Integer(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(), nullable=True),
    sa.Column('refund_amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('partial_refund_amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['released_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_escrow_auto_release', 'escrow_transactions', ['auto_release_date', 'status'], unique=False)
    op.create_index('idx_escrow_buyer', 'escrow_transactions', ['buyer_id', 'status'], unique=False)
    op.create_index('idx_escrow_seller', 'escrow_transactions', ['seller_id', 'status'], unique=False)
    op.create_index('idx_escrow_status', 'escrow_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_escrow_transactions_buyer_id'), 'escrow_transactions', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_escrow_transactions_order_id'), 'escrow_transactions', ['order_id'], unique=True)
    op.create_index(op.f('ix_escrow_transactions_paystack_reference'), 'escrow_transactions', ['paystack_reference'], unique=True)
    op.create_index(op.f('ix_escrow_transactions_seller_id'), 'escrow_transactions', ['seller_id'], unique=False)
    op.create_index(op.f('ix_escrow_transactions_status'), 'escrow_transactions', ['status'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('ORDER_CREATED', 'ORDER_PAID', 'ORDER_SHIPPED', 'ORDER_DELIVERED', 'ORDER_COMPLETED', 'ORDER_CANCELLED', 'PAYMENT_RECEIVED', 'PAYMENT_RELEASED', 'NEW_CHAT_MESSAGE', 'BUYER_INTERESTED', 'DISPUTE_CREATED', 'DISPUTE_RESOLVED', 'ACCOUNT_VERIFIED', 'LOW_STOCK', 'PRODUCT_EXPIRING', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('related_order_id', sa.Integer(), nullable=True),
    sa.Column('related_user_id', sa.Integer(), nullable=True),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('sms_sent', sa.Boolean(), nullable=False),
    sa.Column('sms_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['related_order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_type', 'notifications', ['type', 'created_at'], unique=False)
    op.create_index('idx_notification_user_read', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('quality_rating', sa.Integer(), nullable=True),
    sa.Column('communication_rating', sa.Integer(), nullable=True),
    sa.Column('delivery_rating', sa.Integer(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('response_at', sa.DateTime(), nullable=True),
    sa.Column('is_verified_purchase', sa.Boolean(), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('flagged_reason', sa.Text(), nullable=True),
    sa.Column('helpful_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_review_rating', 'reviews', ['rating'], unique=False)
    op.create_index('idx_review_reviewed_user', 'reviews', ['reviewed_user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_reviews_order_id'), 'reviews', ['order_id'], unique=True)
    op.create_index(op.f('ix_reviews_reviewed_user_id'), 'reviews', ['reviewed_user_id'], unique=False)
    op.create_index(op.f('ix_reviews_reviewer_id'), 'reviews', ['reviewer_id'], unique=False)
    op.create_table('disputes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('escrow_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('raised_by_user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence_description', sa.Text(), nullable=True),
    sa.Column('evidence_image_urls', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('seller_response', sa.Text(), nullable=True),
    sa.Column('seller_evidence_urls', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('seller_response_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_REVIEW', 'RESOLVED', 'CLOSED', name='disputestatus'), nullable=False),
    sa.Column('resolution', sa.Enum('REFUND', 'RELEASE_TO_SELLER', 'PARTIAL_REFUND', 'NO_ACTION', name='disputeresolution'), nullable=True),
    sa.Column('resolution_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('auto_refund_date', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['escrow_id'], ['escrow_transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raised_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dispute_priority_status', 'disputes', ['priority', 'status'], unique=False)
    op.create_index('idx_dispute_status', 'disputes', ['status'], unique=False)
    op.create_index(op.f('ix_disputes_escrow_id'), 'disputes', ['escrow_id'], unique=False)
    op.create_index(op.f('ix_disputes_order_id'), 'disputes', ['order_id'], unique=False)
    op.create_index(op.f('ix_disputes_raised_by_user_id'), 'disputes', ['raised_by_user_id'], unique=False)
    op.create_index(op.f('ix_disputes_status'), 'disputes', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disputes_status'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_raised_by_user_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_order_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_escrow_id'), table_name='disputes')
    op.drop_index('idx_dispute_status', table_name='disputes')
    op.drop_index('idx_dispute_priority_status', table_name='disputes')
    op.drop_table('disputes')
    op.drop_index(op.f('ix_reviews_reviewer_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_reviewed_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_order_id'), table_name='reviews')
    op.drop_index('idx_review_reviewed_user', table_name='reviews')
    op.drop_index('idx_review_rating', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index('idx_notification_user_read', table_name='notifications')
    op.drop_index('idx_notification_type', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_escrow_transactions_status'), table_name='escrow_transactions')
    op.drop_index(op.f('ix_escrow_transactions_seller_id'), table_name='escrow_transactions')
    op.drop_index(op.f('ix_escrow_transactions_paystack_reference'), table_name='escrow_transactions')
    op.drop_index(op.f('ix_escrow_transactions_order_id'), table_name='escrow_transactions')
    op.drop_index(op.f('ix_escrow_transactions_buyer_id'), table_name='escrow_transactions')
    op.drop_index('idx_escrow_status', table_name='escrow_transactions')
    op.drop_index('idx_escrow_seller', table_name='escrow_transactions')
    op.drop_index('idx_escrow_buyer', table_name='escrow_transactions')
    op.drop_index('idx_escrow_auto_release', table_name='escrow_transactions')
    op.drop_table('escrow_transactions')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_seller_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_product_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_buyer_id'), table_name='orders')
    op.drop_index('idx_order_status_created', table_name='orders')
    op.drop_index('idx_order_seller_status', table_name='orders')
    op.drop_index('idx_order_buyer_status', table_name='orders')
    op.drop_table('orders')
    op.drop_table('system_configuration')
    op.drop_index(op.f('ix_products_status'), table_name='products')
    op.drop_index(op.f('ix_products_seller_id'), table_name='products')
    op.drop_index(op.f('ix_products_created_at'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index('idx_product_seller_status', table_name='products')
    op.drop_index('idx_product_created', table_name='products')
    op.drop_index('idx_product_category_status', table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_otp_verifications_user_id'), table_name='otp_verifications')
    op.drop_index('idx_otp_user_type', table_name='otp_verifications')
    op.drop_index('idx_otp_expiry', table_name='otp_verifications')
    op.drop_table('otp_verifications')
    op.drop_index(op.f('ix_admin_actions_timestamp'), table_name='admin_actions')
    op.drop_index(op.f('ix_admin_actions_admin_id'), table_name='admin_actions')
    op.drop_index(op.f('ix_admin_actions_action_type'), table_name='admin_actions')
    op.drop_index('idx_admin_action_type_time', table_name='admin_actions')
    op.drop_index('idx_admin_action_target', table_name='admin_actions')
    op.drop_table('admin_actions')
    op.drop_index(op.f('ix_users_user_type'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_verified', table_name='users')
    op.drop_index('idx_user_type_status', table_name='users')
    op.drop_index('idx_user_location', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_crop_knowledge_crop_name'), table_name='crop_knowledge')
    op.drop_index('idx_crop_name', table_name='crop_knowledge')
    op.drop_index('idx_crop_category', table_name='crop_knowledge')
    op.drop_table('crop_knowledge')
    # ### end Alembic commands ###
